version: '3'
services:
    cantaloupe:
        image: cantaloupe
        build: docker
        ports:
            - 8182:8182
        depends_on:
            - redis
        env_file:
            .env
    redis:
        image: redis:alpine
        hostname: redis
