apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: cantaloupe
  name: cantaloupe
spec:
  ports:
  - name: "8182"
    port: 8182
    targetPort: 8182
  selector:
    io.kompose.service: cantaloupe
status:
  loadBalancer: {}
